Intial search mostly copied from Home
msd-d/PetHub pull request #17
Opened 2021-11-02 22:19 UTC by kepet19

2021-11-02 22:55 UTC, Joergenson commented
sorry misclick

2021-11-02 22:57 UTC, Joergenson commented
Maybe wait for pull request 18 to get merged ;)

2021-11-03 07:28 UTC, kepet19 commented
> Maybe wait for pull request 18 to get merged ;)
Np. 
You can link to the pull_request if you write `#` and then the number `18`
`#18` pr: #18

2021-11-04 06:52 UTC, Joergenson commented on components/styles/search-style.js
> +    color: colors.white,
```suggestion
    color: colors.white,
    borderBottomColor: colors.transparent,
    borderTopColor: colors.transparent,
```

2021-11-04 07:29 UTC, kepet19 commented on components/styles/search-style.js
> +    color: colors.white,
it is implemented

2021-11-05 07:35 UTC, Joergenson requested changes

2021-11-05 07:35 UTC, Joergenson commented on components/styles/post-style.js
> +  whl2: {
Move this to search style :-)

2021-11-05 07:35 UTC, Joergenson commented on components/views/search.js
> +import postStyle from "../styles/post-style";
Remove this

2021-11-05 08:44 UTC, Joergenson approved these changes

2021-11-05 08:49 UTC, Kechr approved these changes

2021-11-05 08:49 UTC, merged