Adds save property to data + access from save-view
msd-d/PetHub pull request #28
Opened 2021-11-05 10:52 UTC by Bokaiii

2021-11-05 10:54 UTC, Joergenson requested changes
:-)

2021-11-05 10:54 UTC, Joergenson commented on components/views/save.js
> +      SaveData: [],
```suggestion
      savedData: [],
```
seems you made little typo

2021-11-05 10:54 UTC, Joergenson commented on components/views/save.js
> +          data={this.state.SaveData}
```suggestion
          data={this.state.savedData}
```

2021-11-05 13:20 UTC, kepet19 requested changes

2021-11-05 13:20 UTC, kepet19 commented on package.json
> +    "expo-cli": "^4.12.12",
Whoops accidentally add expo-cli

2021-11-12 12:17 UTC, Joergenson commented on components/views/save.js
> +export default class SavedScreen extends React.Component {
```suggestion
export default function SavedScreen() {
  const [saveData, setSaveData] = useState([]);
  const [fetching, setFetching] = useState(false);

  const getData = () => {
    Database.getItem("data").then((data) => {
      let filtered = data.filter((items) => items.saved);
      setSaveData(filtered);
    });
  }

  const onRefresh = () => {
    setFetching(true);
    getData();
    setFetching(false);
  }

  useEffect(() => {
    getData();
  }, []);

  return (
    <FlatList
      data={saveData}
      extraData={saveData}
      keyExtractor={(item) => item.id.toString()}
      renderItem={renderSaveScreen}
      refreshing={fetching}
      onRefresh={() => onRefresh}
    />
  );
}

```
you can adapt it like this :)

2021-11-14 09:48 UTC, kepet19 approved these changes

2021-11-14 12:29 UTC, Kechr commented
@Joergenson Have your requested changes been resolved?

2021-11-14 12:31 UTC, Joergenson commented
> @Joergenson Have your requested changes been resolved?

ye

2021-11-14 12:32 UTC, Joergenson approved these changes

2021-11-14 12:35 UTC, merged